name: docker-images

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  main:
    name: hocuspocus

    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push hocuspocus
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          build-args: |
            github_token=${{ secrets.PACKAGES_READ_PERMISSION }}
          tags: |
            ghcr.io/storipress/ec-hocuspocus:latest
